apiVersion: v1
kind: Service
metadata:
  name: nacos-headless-test
  namespace: nacos
  labels:
    app: nacos
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: NodePort
  ports:
    - port: 8848
      name: server
      targetPort: 8848
      nodePort: 32000
  selector:
    app: nacos