kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nfs-client-deploy
  namespace: nacos
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-client-deploy
    spec:
      serviceAccount: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: registry.cn-hangzhou.aliyuncs.com/open-ali/nfs-client-provisioner
          volumeMounts:
            - name: nfs-client
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: my-provisioner
            - name: NFS_SERVER
              value: 10.1.1.99
            - name: NFS_PATH
              value: /home/nfs
      volumes:
        - name: nfs-client
          nfs:
            server: 10.1.1.99
            path: /home/nfs