kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-claim
  namespace: nacos
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-storage
  resources:
    requests:
      storage: 1Mi